### ISSUE TITLE
Adding IAA for non-text bound entities

### ISSUE THREAD

**Issue by serenalotreck** [kldtz/bratiaa#2]
Hi, 

I was wondering if you were thinking about adding a feature to get IAA for non-text bound annotations (specifically, binary relations). From the preliminary literature searching I've done, it looks like this isn't necessarily something that is as routinely done as it is for text-bound relations; the paper that most nearly gets at what I'm looking for is [this one](https://biblio.ugent.be/publication/2000619/file/6765213.pdf). I'm more than happy to open a PR for this feature, but I'm not entirely sure how to define precision and recall for relations. 

**Desired behavior:** Given a project directory of the structure required by bratiaa, in which files have been annotated for *both* entities (text-bound) and relations (non-text bound), calculate the IAA for the annotated relations in addition to the entity IAA already calculated by this package.

Given that, if entities and relations are annotated simultaneously, there may be disagreements in span boundaries for entities that are semantically the same; e.g. in the sentence, "The OsXC3 protein activates transcription of GENE1", one annotator might annotate the relation (OsXC3, activates, GENE1), whereas another might annotate (OsXC3 protein, activates, GENE1). In this case, I would like those relations to be considered the same/in agreement, so I was thinking that treating overlapping entities as equivalent during the calculation of relation IAA would be helpful here. 

Wondering what your thoughts are, and if you'd be open to accepting a PR for this feature!

**Comment by kldtz** [comment]
Hi Serena,

This package was developed for annotation work I did at Jena University. Since I no longer work in research, I have no plans of extending the functionality at the moment.

To achieve what you have in mind, I would start by computing an alignment between the text-bound annotations from different annotators. This is something _bratiaa_ doesn't do. Instead, it simply treats the annotations as sets and computes pair-wise similarities. Computing an alignment is not trivial and sometimes there may not be an optimal solution. I remember reading about [Gamma agreement](https://doi.org/10.1162/COLI_a_00227) and found their alignment approach interesting. Once you have what they call "unitary alignments" (a tuple of text-bound annotations that are considered to be equivalent, one annotation per annotator, possibly containing empty units), you can easily define agreement for relations on top. You could assign an identifier to each unitary alignment and then define your relations as tuples (unitary_alignment_1, unitary_alignment_2, relation_name) and use them to calculate a set similarity or some other measure.

Hope this helps! :)
